;; Generated by matugen - do not edit manually
(defun apply-matugen-colors-to-frame (frame)
  "Apply colors appropriate for FRAME type"
  (with-selected-frame frame
    (if (display-graphic-p frame)
        ;; GUI frame - use matugen colors INCLUDING backgrounds
        ;; Note: internal-border-width is set in main.el default-frame-alist to avoid tiling issues
        (progn
          (set-frame-parameter frame 'background-color "#151218")
          (set-face-attribute 'default frame
                              :background "#151218"
                              :foreground "#e7e0e8")
          (set-face-attribute 'fringe frame
                              :background "#151218")
          (set-face-attribute 'cursor frame
                              :background "#d5bbfc")
          (set-face-attribute 'mode-line frame
                              :background "#2c292f"
                              :foreground "#e7e0e8")
          (set-face-attribute 'mode-line-inactive frame
                              :background "#2c292f"
                              :foreground "#e7e0e8")
          (set-face-attribute 'region frame
                              :background "#513c73")
          (set-face-attribute 'hl-line frame
                              :background "#37333a")
          (set-face-attribute 'window-divider frame
                              :foreground "#958e99")
          (set-face-attribute 'vertical-border frame
                              :foreground "#958e99"))

      ;; Terminal frame - CLEAR frame background parameter
      (progn
        (set-frame-parameter frame 'background-color nil)
        (set-face-attribute 'default frame
                            :foreground "#e7e0e8")
        (set-face-attribute 'cursor frame
                            :background "#d5bbfc")
        (set-face-attribute 'mode-line frame
                            :foreground "#e7e0e8")
        (set-face-attribute 'mode-line-inactive frame
                            :foreground "#e7e0e8")
        (set-face-attribute 'window-divider frame
                            :foreground "#958e99")
        (set-face-attribute 'vertical-border frame
                            :foreground "#958e99")))))

(defun apply-matugen-colors ()
  "Apply material you colors to Emacs"
  (mapc #'apply-matugen-colors-to-frame (frame-list))
  (add-hook 'after-make-frame-functions #'apply-matugen-colors-to-frame)
  (add-hook 'window-configuration-change-hook
            (lambda ()
              (dolist (frame (frame-list))
                (when (not (display-graphic-p frame))
                  (set-frame-parameter frame 'background-color nil)))))
  (advice-add 'load-theme :after
              (lambda (&rest _)
                (run-with-timer 0.1 nil
                                (lambda ()
                                  (mapc #'apply-matugen-colors-to-frame (frame-list)))))))

(provide 'matugen-colors)
