;; Generated by matugen - do not edit manually
(defun apply-matugen-colors-to-frame (frame)
  "Apply colors appropriate for FRAME type"
  (with-selected-frame frame
    (if (display-graphic-p frame)
        ;; GUI frame - use matugen colors INCLUDING backgrounds
        ;; Note: internal-border-width is set in main.el default-frame-alist to avoid tiling issues
        (progn
          (set-frame-parameter frame 'background-color "{{colors.surface.default.hex}}")
          (set-face-attribute 'default frame
                              :background "{{colors.surface.default.hex}}"
                              :foreground "{{colors.on_surface.default.hex}}")
          (set-face-attribute 'fringe frame
                              :background "{{colors.surface.default.hex}}")
          (set-face-attribute 'cursor frame
                              :background "{{colors.primary.default.hex}}")
          (set-face-attribute 'mode-line frame
                              :background "{{colors.surface_container_high.default.hex}}"
                              :foreground "{{colors.on_surface.default.hex}}")
          (set-face-attribute 'mode-line-inactive frame
                              :background "{{colors.surface_container_high.default.hex}}"
                              :foreground "{{colors.on_surface.default.hex}}")
          (set-face-attribute 'region frame
                              :background "{{colors.primary_container.default.hex}}")
          (set-face-attribute 'hl-line frame
                              :background "{{colors.surface_container_highest.default.hex}}")
          (set-face-attribute 'window-divider frame
                              :foreground "{{colors.outline.default.hex}}")
          (set-face-attribute 'vertical-border frame
                              :foreground "{{colors.outline.default.hex}}"))

      ;; Terminal frame - CLEAR frame background parameter
      (progn
        (set-frame-parameter frame 'background-color nil)
        (set-face-attribute 'default frame
                            :foreground "{{colors.on_surface.default.hex}}")
        (set-face-attribute 'cursor frame
                            :background "{{colors.primary.default.hex}}")
        (set-face-attribute 'mode-line frame
                            :foreground "{{colors.on_surface.default.hex}}")
        (set-face-attribute 'mode-line-inactive frame
                            :foreground "{{colors.on_surface.default.hex}}")
        (set-face-attribute 'window-divider frame
                            :foreground "{{colors.outline.default.hex}}")
        (set-face-attribute 'vertical-border frame
                            :foreground "{{colors.outline.default.hex}}")))))

(defun apply-matugen-colors ()
  "Apply material you colors to Emacs"
  (mapc #'apply-matugen-colors-to-frame (frame-list))
  (add-hook 'after-make-frame-functions #'apply-matugen-colors-to-frame)
  (add-hook 'window-configuration-change-hook
            (lambda ()
              (dolist (frame (frame-list))
                (when (not (display-graphic-p frame))
                  (set-frame-parameter frame 'background-color nil)))))
  (advice-add 'load-theme :after
              (lambda (&rest _)
                (run-with-timer 0.1 nil
                                (lambda ()
                                  (mapc #'apply-matugen-colors-to-frame (frame-list)))))))

(provide 'matugen-colors)
