#-*- mode: org -*-
#+STARTUP: showall

* 2022

** 2022-09 сентября

*** 2022-09-18 Воскресенье
**** Пример записи                                                  :JOURNAL:
:LOGBOOK:
CLOCK: [2022-09-18 Вс 17:00]--[2022-09-18 Вс 17:00] =>  0:00
:END:
<2022-09-18 Вс>
[2022-09-18 Вс 17:00]

[[file:~/org/personal.org::*Вот это мне нравится][Вот это мне нравится]]

*** 2022-09-19 Понедельник

*** 2022-09-20 Вторник

*** 2022-09-23 Пятница

*** 2022-09-25 Воскресенье

*** 2022-09-26 Понедельник

*** 2022-09-27 Вторник

** 2022-10 октября

*** 2022-10-03 Понедельник

*** 2022-10-06 Четверг

*** 2022-10-12 Среда

*** 2022-10-14 Пятница

*** 2022-10-15 Saturday

*** 2022-10-16 Sunday

*** 2022-10-18 Вторник
**** Странный сон 2022-10-18                                  :JOURNAL:DREAM:
:LOGBOOK:
CLOCK: [2022-10-18 Вт 11:49]--[2022-10-18 Вт 11:50] =>  0:01
:END:
<2022-10-18 Вт>
[2022-10-18 Вт 11:49]
Странный сон. Снилось, будто мне пришлось по делам вернуться в Россию,
не знаю там, продать что-то или просто приехал повидаться с людьми.
Поехал было в офис Самсунга, но развернулся прямо у порога офиса --
вдруг меня увидит Тимур и заставит теперь работать их офиса.

*** 2022-10-21 Пятница

*** 2022-10-27 Четверг

** 2022-11 ноября

*** 2022-11-03 Четверг

*** 2022-11-11 Пятница

* 2023
** 2023-03 марта
*** 2023-03-30 Четверг
**** Начинаю потихоньку вспоминать emacs                            :JOURNAL:
:LOGBOOK:
CLOCK: [2023-03-30 Чт 15:54]--[2023-03-30 Чт 15:55] =>  0:01
:END:
<2023-03-30 Чт>
[2023-03-30 Чт 15:54]

Добавил репозиторий dotfiles, обновил spacemacs
** 2023-04 April
*** 2023-04-20 Thursday
*** 2023-04-26 Wednesday
*** 2023-04-27 Thursday
*** 2023-04-28 Friday
** 2023-05 May
*** 2023-05-02 Tuesday
*** 2023-05-03 Wednesday
*** 2023-05-04 Thursday
*** 2023-05-08 Monday
*** 2023-05-16 Tuesday
*** 2023-05-30 Tuesday
** 2023-06 June
*** 2023-06-01 Thursday
**** Hahaha                                                         :JOURNAL:
:LOGBOOK:
CLOCK: [2023-06-01 Thu 13:38]--[2023-06-01 Thu 13:38] =>  0:00
:END:
<2023-06-01 Thu>
[2023-06-01 Thu 13:38]
**** Test test test                                                 :JOURNAL:
:LOGBOOK:
CLOCK: [2023-06-01 Thu 15:56]
:END:
<2023-06-01 Thu>
[2023-06-01 Thu 15:56]

[[mu4e:msgid:note_217943@rnd-gitlab-eu-c.huawei.com][Re: duck | Avoid rounding errors when converting time units to ticks. (!993)]]
**** Test using email attachment in org-mode                        :JOURNAL:
:LOGBOOK:
CLOCK: [2023-06-01 Thu 17:29]--[2023-06-01 Thu 17:29] =>  0:00
:END:
<2023-06-01 Thu>
[2023-06-01 Thu 17:28]

[[mu4e:msgid:874jnrgq4u.fsf@nerovny][One more test]]
Looks like it works!
*** 2023-06-09 Friday
*** 2023-06-30 Friday
**** Notes on CI job for HM-lotto                                   :JOURNAL:
:LOGBOOK:
CLOCK: [2023-06-30 Fri 11:22]--[2023-06-30 Fri 11:22] =>  0:00
:END:
<2023-06-30 Fri>
[2023-06-30 Fri 11:21]

[[file:~/dev/lotto/.ci/hm-lotto.Dockerfile::FROM rnd-gitlab-eu-c.huawei.com:8443/germany-research-center/dresden-lab/hm-mobile/scripts/docker/hmbase22:latest]]

So, the main script hmbaseXX provides an infrastructure that may be used to run HM build scripts from hm-grc-scripts.
1. I need a token to access this repository for CI job (dresden-lab/hm-mobile). It is not built automatically so probably I must create some CI job that builds such an image for me
2. Next, I need to prepare a separate dockerfile for s4c/lotto CI job, it must download hm-grc-scripts automatically including all submodules so I need a token to dresden-lab/hongmengos/*
3. I must utilize some custom long living branch for uvmm and hm-verif-kernel so I need a token for dresden-lab/ententeich

The step 1 is very heavy and it will produce a giant container -- it is better to utilize the HM SDK for such purposes -- I only need to build an application (a plugin for uvmm), does not need to run tests on CI yet.
However, it requires a modified system headers
**** Notes after week 26                                            :JOURNAL:
:LOGBOOK:
CLOCK: [2023-06-30 Fri 16:54]--[2023-06-30 Fri 16:58] =>  0:04
:END:
<2023-06-30 Fri>
[2023-06-30 Fri 16:54]

I have successfully started to work more time then on previous week.
The solution is just to perform simple work after lunch -- code review,
discussion, very simple coding.

Leave all hard things to the first part of a day, and complete it before the lunch.

I have prepared a patch that provides a build stage for LOTTO CI for HM-lotto,
it works nice.
I have learned something about docker, I like this thing.

Next week, I definitely need to finish the Duck-related task,
complete my activities there.
It is not as hard as it looks like but it is annoying.

I also need to discuss with Diogo my LOTTO plan and deadlines.
** 2023-07 July
*** 2023-07-04 Tuesday
**** Proposal: use livepatch to update vanilla binaries on the fly  :JOURNAL:
:LOGBOOK:
CLOCK: [2023-07-04 Tue 16:21]--[2023-07-04 Tue 16:23] =>  0:02
:END:
<2023-07-04 Tue>
[2023-07-04 Tue 16:21]

[[file:~/dev/lotto/src/hm-lotto/livepatch.c]]
Provide all needed functions that do the following:
1) Hotpatch hypervisor driver in HM kernel in runtime to allow
control of vCPU switching
2) Alter behavior of vm.elf in runtime as well
*** 2023-07-10 Monday
**** There is a problem here :JOURNAL:
:LOGBOOK:
CLOCK: [2023-07-10 Mon 09:55]--[2023-07-10 Mon 09:56] =>  0:01
:END:
<2023-07-10 Mon>
[2023-07-10 Mon 09:55]

[[file:~/dev/lotto/src/hm-lotto/livepatch.c::livepatch_alloc_mem(size_t size)]]

It looks like CFI produces a trap here -- need to check with objdump
*** 2023-07-11 Tuesday
*** 2023-07-14 Friday

*** 2023-07-17 Monday
**** Test                                                           :JOURNAL:
:LOGBOOK:
CLOCK: [2023-07-17 Mon 14:13]--[2023-07-17 Mon 14:13] =>  0:00
:END:
<2023-07-17 Mon>
[2023-07-17 Mon 14:13]
*** 2023-07-18 Tuesday

*** 2023-07-20 Thursday
**** It worked                                                      :JOURNAL:
:LOGBOOK:
CLOCK: [2023-07-20 Thu 18:05]--[2023-07-20 Thu 18:05] =>  0:00
:END:
<2023-07-20 Thu>
[2023-07-20 Thu 18:05]

[[file:~/org/dev.org::*Integration of Raspberry PI into Duck CI][Integration of Raspberry PI into Duck CI]]

*** 2023-07-21 Friday
**** Migrate to Vanilla emacs                                       :JOURNAL:
:LOGBOOK:
CLOCK: [2023-07-21 Fri 17:01]--[2023-07-21 Fri 17:02] =>  0:01
:END:
<2023-07-21 Fri>
[2023-07-21 Fri 17:01]

Today I have finally migrated to vanilla Emacs with some additional packages.
My productivity was heavily boosted and I like my new experience.
This helped me with my procrastination a lot, I have wrote several
useful pieces of important projects, though not so many yet.

No I will stop to configure my editor and focus on my primary goals.

*** 2023-07-24 Monday
* Turn on device
#+BEGIN_SRC bash
./USBswitchCmd 1
#+END_SRC

* Turn off device
#+BEGIN_SRC bash
./USBswitchCmd 0
#+END_SRC
