;; Generated by matugen - do not edit manually
(defun apply-matugen-colors-to-frame (frame)
  "Apply colors appropriate for FRAME type"
  (with-selected-frame frame
    (if (display-graphic-p frame)
        ;; GUI frame - use matugen colors INCLUDING backgrounds
        (progn
          (set-frame-parameter frame 'internal-border-width 22)
          (set-frame-parameter frame 'background-color "#0f1417")
          (set-face-attribute 'default frame
                              :background "#0f1417"
                              :foreground "#dfe3e7")
          (set-face-attribute 'fringe frame
                              :background "#0f1417")
          (set-face-attribute 'cursor frame
                              :background "#90cef4")
          (set-face-attribute 'mode-line frame
                              :background "#262b2e"
                              :foreground "#dfe3e7")
          (set-face-attribute 'mode-line-inactive frame
                              :background "#262b2e"
                              :foreground "#dfe3e7")
          (set-face-attribute 'region frame
                              :background "#004c69")
          (set-face-attribute 'hl-line frame
                              :background "#313539")
          (set-face-attribute 'window-divider frame
                              :foreground "#8b9297")
          (set-face-attribute 'vertical-border frame
                              :foreground "#8b9297"))

      ;; Terminal frame - CLEAR frame background parameter
      (progn
        (set-frame-parameter frame 'background-color nil)
        (set-face-attribute 'default frame
                            :foreground "#dfe3e7")
        (set-face-attribute 'cursor frame
                            :background "#90cef4")
        (set-face-attribute 'mode-line frame
                            :foreground "#dfe3e7")
        (set-face-attribute 'mode-line-inactive frame
                            :foreground "#dfe3e7")
        (set-face-attribute 'window-divider frame
                            :foreground "#8b9297")
        (set-face-attribute 'vertical-border frame
                            :foreground "#8b9297")))))

(defun apply-matugen-colors ()
  "Apply material you colors to Emacs"
  (mapc #'apply-matugen-colors-to-frame (frame-list))
  (add-hook 'after-make-frame-functions #'apply-matugen-colors-to-frame)
  (add-hook 'window-configuration-change-hook
            (lambda ()
              (dolist (frame (frame-list))
                (when (not (display-graphic-p frame))
                  (set-frame-parameter frame 'background-color nil)))))
  (advice-add 'load-theme :after
              (lambda (&rest _)
                (run-with-timer 0.1 nil
                                (lambda ()
                                  (mapc #'apply-matugen-colors-to-frame (frame-list)))))))

(provide 'matugen-colors)
